### ISSUE TITLE
examples not working...?

### ISSUE THREAD

**Issue by DanyboyInSwitzerland** [turbyho/DABDUINO#3]
When trying to compile the example #1 with the arduino IDE 1.8.0 it will stop with the following message:

DABDUINO_example_1:15: error: no matching function for call to 'DABDUINO::DABDUINO(int, int, int, int)'

The line it takes reference to is the following:
DABDUINO dab = DABDUINO(_DAB_SERIAL_PORT, _DAB_RESET_PIN, _DAB_DAC_MUTE_PIN, _DAB_SPI_CS_PIN);

It appears even the example doesn't work...?
Maybe this is an issue with progressing versions of the Arduino-IDE, while the library is still from april 2017?

**Comment by GamalBorhan** [comment]
I have checked this out, it works fine for me. Perhaps the Arduino could not find the library. Please double check that the library is available (from the Arduino IDE, open the Libraries manager and type its name. Arduino IDE will list it and you can make sure it is installed or if not reinstall it. 
P.s: I am using Arduino 1.8.5.

**Comment by DanyboyInSwitzerland** [comment]
Hi Gamal!
I did not think about verifying whether arduino recognises the library...
With rising hope to have found the culprit, I checked the library manager - got the 1.0.1... :(
...and scratch my info concerning IDE-version -. I'm actually on 1.8.6, must've been fingertroubles...

What's bugging me, is that the example doesn't work...
If it was code written by me, I'd shrug it off and search for the mistake I did... ;)
But the example is usually the place where I turn to when my own code doesn't work...

**Comment by DanyboyInSwitzerland** [comment]
...oh...
,,,mah...
...gahd...
...this is gonna be SO embarassing...
...just make sure you really select the right board...
...I was sold an arduino zero m0 compatible board...
...everything works just fine now... :)
