### ISSUE TITLE
Decoding RDS data using the DABDUINO library

### ISSUE THREAD

**Issue by GamalBorhan** [turbyho/DABDUINO#4]
Hello DABDUINO experts,

I need help with RDS decoding. I used the getRdsPIcode() method to successfully retrieve the station's pi code but I could not retrieve the RDS raw data using the getRDSrawData() method. I suspect that there is a mistake in the later's code, there suppose to be four blocks A,B,C,D within the RDS packet but the method repeats the blockB part multiple times? Did anybody use this method (or something else) and managed to extract the RDS data (would you please be so kind and post your working code here)?

Thanks and best regards,
Gamal

**Comment by turbyho** [comment]
Hi Gamal,
please check my today fix of the getRDSrawData.

**Comment by GamalBorhan** [comment]
Thanks Tomas!
